cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'asdf'
brew 'gpg2'

cask '1password'
cask 'alfred'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2'
cask 'karabiner-elements'
cask 'ngrok'
cask 'notion'
cask 'postman'
cask 'protonvpn'
cask 'rectangle-pro'
cask 'tidal'
cask 'visual-studio-code'
cask 'vlc'
