cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'gpg2'

cask '1password'
cask 'alfred'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2'
cask 'notion'
cask 'postman'
cask 'protonvpn'
cask 'sizeup'
cask 'tidal'
cask 'visual-studio-code'
cask 'vlc'
